title: Chang Shuo (Johnson) Chen
logo: "/images/photo.jpeg?raw=true"
description: >
  Machine Learning / Computer Vision Engineer
  <br>
  Edge AI & AI System Integration
  <br><br>
  B.S. in Management Information Systems, National Chengchi University
linkedin_url: "https://www.linkedin.com/in/chang-shuo-johnson-chen-83013a193/"
theme: jekyll-theme-minimal
