title: Chang Shuo (Johnson) Chen
logo: "/images/photo.jpeg?raw=true"
description: >
  Bachelor's degree in Management Information Systems, National Chengchi University
  <br><br>
  Machine/Deep Learning, Computer Vision
  <br><br>
  <a href="https://www.linkedin.com/in/chang-shuo-johnson-chen-83013a193/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
